### 精准率和召回率的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets

In [2]:
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver="liblinear")
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

0.9755555555555555

In [5]:
y_predict = log_reg.predict(X_test)  # 得到预测值

In [6]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [7]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [8]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [9]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [11]:
log_reg.decision_function(X_test)[:10]

array([-22.05699305, -33.02941229, -16.21334491, -80.37913286,
       -48.251232  , -24.54005048, -44.39164957, -25.04292997,
        -0.97828095, -19.71742418])

In [12]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
decision_scores = log_reg.decision_function(X_test)

In [14]:
np.min(decision_scores)

-85.68609766666843

In [15]:
np.max(decision_scores)

19.88959586250276

In [16]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [17]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [18]:
precision_score(y_test, y_predict_2)

0.96

In [19]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [20]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [21]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]], dtype=int64)

In [22]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [23]:
recall_score(y_test, y_predict_3)

0.8888888888888888